### ISSUE TITLE
diagnostics improvements TODO list

### ISSUE THREAD

**Issue by japaric** [trifectatechfoundation/sudo-rs#181]
- [x] `sudo -g ghosts` where the target group does not exist. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/flag_group.rs#L118)
  - ogsudo: `sudo: unknown group: ghosts`
  - sudo-rs: `Error: GroupNotFound("ghosts")`
- [x] `sudo -u ghost` where the target user does not exist. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/flag_user.rs#L130)
  - ogsudo: `sudo: unknown user: ghost`
  - sudo-rs: `UserNotFound("ghost")`
- [x] sudoers is group writable. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers.rs#L36-L39)
  - ogsudo: `/etc/sudoers is owned by gid 1234, should be 0`
  - sudo-rs: `Error: Configuration("no valid sudoers file: /etc/sudoers.test cannot be group-writable")"`
- [x] sudoers is world writable. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers.rs#L18)
  - ogsudo: `sudo: /etc/sudoers is world writable`
  - sudo-rs: `Error: Configuration("no valid sudoers file: /etc/sudoers.test cannot be world-writable")`
- [x] sudoers is not owned by root. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers.rs#L65-L68)
  - ogsudo: `sudo: /etc/sudoers is owned by uid 1000, should be 0`
  - sudo-rs: `Error: Configuration("no valid sudoers file: /etc/sudoers.test cannot be world-writable")`
- [x] user is in sudoers but other user spec constraints are not met. relevant tests: [cmnd](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers/cmnd.rs#L28-L31) (2 tests), [run_as](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers/run_as.rs#L51-L54) (6 tests)
  - ogsudo: `user root is not allowed to execute '/bin/true' as root`
  - sudo-rs: `Error: Authentication("no permission")`
- [x] sudoers: hostname mismatch. relevant tests: [1](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers/host_list.rs#L30-L34), [2](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers/host_list.rs#L75-L78)
  - ogsudo: `root is not allowed to run sudo on HOSTNAME`
  - sudo-rs: `Error: Authentication("no permission")`
- [x] user is not in sudoers. relevant tests: [1](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers/user_list.rs#L16), [2](https://github.com/memorysafety/sudo-rs/blob/2a8078800fac8513fedbbff1a33cf62008af6637/test-framework/sudo-compliance-tests/src/sudoers/user_list.rs#L145)
  - ogsudo: `root is not in the sudoers file`
  - sudo-rs: `Error: Authentication("no permission")`
- [x] program not found in PATH. [relevant test](https://github.com/memorysafety/sudo-rs/blob/db05ee3a1c90139784f3b2530d4ba4c991bbdef9/test-framework/sudo-compliance-tests/src/path_search.rs#L46)
  - ogsudo: `sudo: my-script: command not found`
  - sudo-rs: `Error: InvalidCommand`
- [x] `sudo -g #1234` where the target grout does not exist. [relevant test](https://github.com/memorysafety/sudo-rs/blob/c67e1c88;03d3aa0f830fe3472c78d8eb2ca31bf9/test-framework/sudo-compliance-tests/src/flag_group.rs#L99)
  - ogsudo: `sudo: unknown group: #1234`
  - sudo-rs: `Error: GroupNotFound("#1234")`
- [x] `sudo -u #1234` where the target user does not exist. [relevant test](https://github.com/memorysafety/sudo-rs/blob/c67e1c8803d3aa0f830fe3472c78d8eb2ca31bf9/test-framework/sudo-compliance-tests/src/flag_user.rs#L114)
  - ogsudo: `sudo: unknown user: #1234`
  - sudo-rs: `Error: UserNotFound("#1234")`
- [x] invoking user is not in the passwd database. [relevant test](https://github.com/memorysafety/sudo-rs/blob/a9a94334d3ac4e8c921e672d7ac900988936080f/test-framework/sudo-compliance-tests/src/misc.rs#L18-L21)
  - ogsudo: `Error: UserNotFound("current user")`
  - sudo-rs: `sudo: you do not exist in the passwd database`
- [x] using `--chdir` flag when CWD is not set in sudoers. [relevant test](https://github.com/memorysafety/sudo-rs/blob/196031bbe87169e11e2a6c0fabdc5c8f7617fec5/test-framework/sudo-compliance-tests/src/flag_chdir.rs#L16)
  - ogsudo: `you are not permitted to use the -D option with /path/to/command`
  - sudo-rs: `authentication failed, no permission` (could be more precise)
- [x] no password provided. [relevant test](https://github.com/memorysafety/sudo-rs/blob/196031bbe87169e11e2a6c0fabdc5c8f7617fec5/test-framework/sudo-compliance-tests/src/pass_auth.rs#L58)
  - ogsudo: `no password was provided`
  - sudo-rs: `sudo-rs: PAM error: PAM returned an error (AuthError): Authentication failure` (looks like debug representation)
- [x] wrong password provided. [relevant test](https://github.com/memorysafety/sudo-rs/blob/196031bbe87169e11e2a6c0fabdc5c8f7617fec5/test-framework/sudo-compliance-tests/src/pass_auth.rs#L39)
  - ogsudo: `incorrect password attempt`
  - sudo-rs: `sudo-rs: PAM error: PAM returned an error (AuthError): Authentication failure` (looks like debug representation)
- [x] `SHELL=/does/not/exist sudo -s`. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2ddf591565dbc7cc1c4e6f6e686e75fb85f6fb19/test-framework/sudo-compliance-tests/src/flag_shell.rs#L172)
  - ogsudo: `sudo: /does/not/exist: command not found`
  - sudo-rs: `IO error: No such file or directory` (it could mention the program's path)
- [x] `SHELL=/non/executable/file sudo -s`. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2ddf591565dbc7cc1c4e6f6e686e75fb85f6fb19/test-framework/sudo-compliance-tests/src/flag_shell.rs#L194)
  - ogsudo: `sudo: /non/executable/file: command not found`
  - sudo-rs: `IO error: Permission denied` (it could mention the program's path)
- [x] `sudo -u ferris -i` where the target user's shell does not exist. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2ddf591565dbc7cc1c4e6f6e686e75fb85f6fb19/test-framework/sudo-compliance-tests/src/flag_login.rs#L198)
  - ogsudo: `sudo: /does/not/exist: command not found`
  - sudo-rs: `IO error: No such file or directory` (it could mention the program's path)
- [x] `sudo -u ferris -i` where the target user does not have sufficient permissions to use the shell. [relevant test](https://github.com/memorysafety/sudo-rs/blob/2ddf591565dbc7cc1c4e6f6e686e75fb85f6fb19/test-framework/sudo-compliance-tests/src/flag_login.rs#L220)
  - ogsudo: `sudo: /root/some-shell: command not found`
  - sudo-rs: `IO error: Permission denied` (it could mention the program's path)

**Comment by squell** [comment]
I've left some of the bullet lists open, as we just give a (temporarily playful) "not allowed" message; I think that is a pretty good error message; as soon as we do `sudo -l` we can easily retrieve more detailed information *why* authentication failed (if we care to inform the user).

One reason to delay that would be that right now the `check_permission` function is pretty tiny (and "in the critical path"), whereas anything we would do for `sudo -l` would not be.

**Comment by squell** [comment]
Using sudo-rs a bit, I think the error messages are still very clunky, like:
`sudo-rs: PAM error: PAM returned an error (AuthError): Authentication failure`.

This makes sense from a programmer POV, but this is one of the error modes normal users that don't know (or need to know) what PAM is are going to see a lot and it should be a nice message like 
```
sudo-rs: authentication failed
```

**Comment by squell** [comment]
Note: error messages are still a bit messy, e.g. extra quotes around
```
sudo-rs: `"foo"': command not found
```
